### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to_csv' (Twitter scraper return null)

### ISSUE THREAD

**Issue by uncloak** [MLH-Fellowship/Social-BERTerfly#22]
Hi and thanks for this cool project!

First issue on requirements, dataclasses==0.8 is not available on latest python, staying on 0.6 would be fine.
Also pyasn1-modules is already part of dist-package in ubuntu 20.04, I had to comment it out since it creates an error.

Now to the main issue. Once successfully installed on a clean ubuntu, the server starts fine, but when I submit a handle I get the following trace:

```
127.0.0.1 - - [17/Jan/2021 07:09:36] "OPTIONS /tweet_pred HTTP/1.1" 200 -
failed on_status, Failed to send request: Only unicode objects are escapable. Got None of type <class 'NoneType'>.
[2021-01-17 07:09:40,698] ERROR in app: Exception on /tweet_pred [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Social-BERTerfly/server/app.py", line 36, in tweet
    tweet_return(user_handle)
  File "/opt/Social-BERTerfly/server/twitterscraper.py", line 82, in tweet_return
    twitter.get_user_tweets(str(tweet_handle)).to_csv(tweet_path)
AttributeError: 'NoneType' object has no attribute 'to_csv'
127.0.0.1 - - [17/Jan/2021 07:09:40] "POST /tweet_pred HTTP/1.1" 500 -
```

Looks like the twitter scraper does not return any results.
My instance is on GCP and firewall allow external calls... 

After looking a bit in the code I see that auth credentials are needed amd that this is not a credential free scraper like twint... too bad :)

So I think your readme should mention this part about creating a .env file, and about dependency issues as well.

**Comment by V2dha** [comment]
Thanks for pointing out the issue we'll update the readme and fix dependency issues accordingly.

**Comment by V2dha** [comment]
Updated the requirements.txt which no longer requires dataclasses or any other library not consistent with the latest python version.
